backend/models/UserForm.php
<?php
namespace backend\models;

use common\models\User;
use yii\base\Model;
use Yii;

/**
 * Class UserForm Форма сохдания и редактирования юзера в админке
 * @package backend\models

 * @property string $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $roles
 * @property string $permissions
 * @property string $isNewRecord
 *
 */
class UserForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $roles;
    public $permissions;
    public $id;
    public $isNewRecord=true;

    public function __construct($isNewRecord=true){
        $this->isNewRecord = $isNewRecord;

    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = [
            ['username', 'filter', 'filter' => 'trim'],
            [['username', 'email'],'required', 'message'=>\Yii::t('auth', 'can\'t be empty')],
            ['username', 'string', 'min' => 2, 'max' => 100, 'tooShort' => \Yii::t('auth', 'minimum character',['n'=>2]), 'tooLong' => \Yii::t('auth', 'maximum character',['n'=>255])],

            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'email'],

            ['password', 'string', 'min' => 6, 'tooShort' => \Yii::t('auth', 'minimum character',['n'=>6])],
            [['roles','id','permissions'], 'safe'],
            [['id'], 'integer']
        ];
        if($this->isNewRecord){
            $rules[] = ['password', 'required', 'message'=>\Yii::t('auth', 'can\'t be empty')];

            $rules[] = ['username', 'unique', 'targetClass' => '\common\models\User', 'message' => \Yii::t('auth', 'This username has already been taken.')];
            $rules[] = ['email', 'unique', 'targetClass' => '\common\models\User', 'message' => \Yii::t('auth', 'This email address has already been taken.')];
        }
        return $rules;

    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */
    public function signup()
    {
        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            $user->setActiveStatus();
            if ($user->save()) {
                Yii::$app->authManager->revokeAll($user->id); //Удаляем все роли/пермишены юзера

                if(count($this->roles)){
                    foreach($this->roles as $role){
                        $newRole = Yii::$app->authManager->getRole($role); //создаем объект роли по имени
                        Yii::$app->authManager->assign($newRole, $user->id);
                    }
                }
                if(count($this->permissions)){
                    foreach($this->permissions as $perm){
                        $newPerm = Yii::$app->authManager->getPermission($perm); //создаем объект роли по имени
                        Yii::$app->authManager->assign($newPerm, $user->id);
                    }
                }
                return $user;
            }
        }
        return null;
    }

    /**
     * Изменение  пользователя
     *
     * @return true/false saved 2 model User and UserProfile
     */
    public function update()
    {
        if ($this->validate()) {
            /**  @var $user User*/
            $user = User::findOne($this->id);

            $user->username = $this->username;
            $user->email = $this->email;
            if($this->password)
                $user->setPassword($this->password);
            $user->generateAuthKey();
            $user->setActiveStatus();
            if ($user->save()) {
                /**
                 * Юзера сохранили сохраняем права
                 */
                Yii::$app->authManager->revokeAll($user->id); //Удаляем все роли/пермишены юзера

                if(count($this->roles)){
                    foreach($this->roles as $role){
                        $newRole = Yii::$app->authManager->getRole($role); //создаем объект роли по имени
                        Yii::$app->authManager->assign($newRole, $user->id);
                    }
                }
                if(count($this->permissions)){
                    foreach($this->permissions as $perm){
                        $newPerm = Yii::$app->authManager->getPermission($perm); //создаем объект роли по имени
                        Yii::$app->authManager->assign($newPerm, $user->id);
                    }
                }
                return true;
            }
        }

        return false;
    }

    /**
     * Массив лэйблов локализованный
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'username' => \Yii::t('auth','username'),
            'email' =>\Yii::t('auth','email'),
            'password' => \Yii::t('auth','password'),
        ];
    }
}

common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;


/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $email_confirm_token
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
	const SEX_MALE = 1;     // М
	const SEX_FEMALE = 0;   // Ж

    const STATUS_DELETED = 0;
    const STATUS_NOACTIVE = 5;
    const STATUS_ACTIVE = 10;

    public function getActiveStatus()
    {
        return self::STATUS_ACTIVE;
    }

    public function isActive()
    {
        return $this->status===self::STATUS_ACTIVE;
    }

    public function setActiveStatus()
    {
        $this->status = self::STATUS_ACTIVE;
    }

    public function getStatusLabel()
    {
        $label=[0=>'Deleted',5=>'No Active',10=>'Active'];
        return $label[$this->status];
    }

    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_NOACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_NOACTIVE]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::find()
            ->where(['email' => $email, 'status' => self::STATUS_ACTIVE])
            ->one();
    }

    public static function findNoActivateByEmail($email)
    {
        return static::find()
            ->where(['email' => $email,'status'=>self::STATUS_NOACTIVE])
            ->exists();
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }
        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by email confirm token
     *
     * @param string $token email confirm token
     * @return static|null
     */
    public static function findByEmailConfirmToken($token)
    {
        return static::findOne([
            'email_confirm_token' => $token
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * Finds out if email confirm token is valid
     *
     * @param string $token email confirm token
     * @return boolean
     */
    public static function isEmailConfirmTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordEmailConfirmExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Set status active
     *
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new email confirm token
     */
    public function generateEmailConfirmToken()
    {
        $this->email_confirm_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * Removes email confirm token
     */
    public function removeEmailConfirmToken()
    {
        $this->email_confirm_token = null;
    }

    public function confirmEmail()
    {
        $this->setStatus(self::STATUS_ACTIVE);
        $this->removeEmailConfirmToken();
        return $this->save();
    }

	/* * */

	public function getProfile()
	{
		return $this->hasOne('common\models\UserProfile', ['id_user' => 'id']);
	}

	static public function getAllToList()
	{
		$album = new static();
		$list = $album
			->find()
			->orderBy('username')
			->asArray()
			->all();

		$keys = array_map(
			function ($item) {
				return $item['id'];
			}, $list);

		$values = array_map(
			function ($item) {
				return $item['username'] . '(' . $item['email'] . ')';
			}, $list);

		return array_combine($keys, $values);
	}

    /**
     * Связь пользователя с альбомами
     * @return \yii\db\ActiveQuery
     */
    public function getAlbums()
    {
        return $this
            ->hasMany('common\models\Album', ['id_user' => 'id']);
    }

    /**
     * Возвращает все альбомы пользователя
     * @return array
     */
    public function getAlbumsToList()
    {
        return ArrayHelper::map(
            $this->getAlbums()->asArray()->all(),
            'id',
            'title'
        );
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => \Yii::t('auth','username'),
            'email' =>\Yii::t('auth','email'),
            'status' => \Yii::t('auth','status'),
            'created_at' => \Yii::t('auth','created_at'),
            'updated_at' => \Yii::t('auth','updated_at'),
            'password' => \Yii::t('auth','password'),
        ];
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use backend\models\UserForm;
use backend\models\RoleForm;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use vova07\fileapi\actions\UploadAction as FileAPIUpload;
use yii\helpers\Url;
/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    /**
     * Поведение
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['r_user'], //все действия по работе с юзерами только для админа
                    ],
                    [
                        'actions' => ['create','update','delete'],
                        'allow' => true,
                        'roles' => ['w_user'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $userForm = new UserForm();
        if ($userForm->load(Yii::$app->request->post())) {
            if ($userForm->signup()) {
                Yii::$app->session->setFlash('success', \Yii::t('auth', 'User successful create'));
                return $this->redirect('index');
            }
        }

        return $this->render('create', [
            'userForm' => $userForm
        ]);
    }

    /**
     * Updates an existing UserForm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        /**  @var $user User*/
        $user = User::findOne($id);
        $userForm = new UserForm(false);
        $userForm->attributes = $user->attributes; //суем данные из User в форму



        if ($userForm->load(Yii::$app->request->post())) {
            if ($userForm->update()) {
                return $this->redirect(['index']);
            }
        }
        $userForm->roles = array_keys(Yii::$app->authManager->getRolesByUser($user->getId()));
        $userForm->permissions = array_keys(Yii::$app->authManager->getAssignments($user->getId()));
        return $this->render('create', [
            'userForm' => $userForm,
        ]);
    }


    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModelUser($id)->delete();
        Yii::$app->session->setFlash('success', \Yii::t('auth', 'User successful deleted'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelUser($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Ooops, unexpected error');
        }
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use nex\chosen\Chosen;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $userForm backend\models\UserForm*/

?>


<div class="box">
    <div class="box-body">

        <?php $form = ActiveForm::begin(); ?>


        <?= $form->field($userForm, 'username')->textInput(['maxlength' => 100]) ?>
        <?= $form->field($userForm, 'email') ?>
        <?= $form->field($userForm, 'password',[
            'template' => $userForm->isNewRecord?'<div>{label}{input}{hint}{error}</div>':'<div>{label}(введите для смены){input}{hint}{error}</div>',
        ]) ?>
        <?= Chosen::widget([
            'placeholder' => 'Выберите роли',
            'model' => $userForm,
            'attribute' => 'roles',
            'items' => ArrayHelper::map(Yii::$app->authManager->getRoles(), 'name', 'description'),
            'multiple' => true,
        ]); ?>
        <?= Chosen::widget([
            'placeholder' => 'Выберите права',
            'model' => $userForm,
            'attribute' => 'permissions',
            'items' => ArrayHelper::map(Yii::$app->authManager->getPermissions(), 'name', 'description'),
            'multiple' => true,
        ]); ?>
        <div class="help-block"></div>
        <?= Html::error($userForm, 'roles', [
            'class' => 'help-block'
        ])
        ?>
        <?= Html::activeInput('hidden', $userForm, 'id') ?>



        <div class="form-group">
            <?= Html::submitButton($userForm->isNewRecord ? Yii::t('auth', 'Create') : Yii::t('auth', 'Update'), ['class' => $userForm->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>
</div>
</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?php // $form->field($model, 'auth_key') ?>

    <?php // $form->field($model, 'password_hash') ?>

    <?php // $form->field($model, 'password_reset_token') ?>

    <?php  echo $form->field($model, 'email') ?>

    <?php  echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php  echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'email_confirm_token') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/create.php
<?php


use yii\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $userForm backend\models\UserForm */


$this->title = \Yii::t('auth', 'Create user');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('auth', 'users'), 'url' => ['/user']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="user-create">

        <div class="col-sm-5">

            <p><?= \Yii::t('auth', 'Please fill out the following fields to signup:') ?></p>

            <?php
            echo $this->render('_form', ['userForm' => $userForm])
            ?>


        </div>
    </div>
</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/** @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>

    <div class="page-header">
        <div class="panel-heading-controls">
            <?= Html::a('<i class="btn-label icon fa fa-plus"></i> '.\Yii::t('auth','Create user'), ['create'], ['class' => 'btn btn-labeled btn-primary no-margin-t']) ?>
        </div>
    </div>



    <div class="box">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "<div class='box-body'>{items}</div><div class='box-footer'><div class='row'><div class='col-sm-6'>{summary}</div><div class='col-sm-6'>{pager}</div></div></div>",
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute'=>'id',
                'format'=>'raw',
                'value'=>function($data){
                    return Html::a($data->id,\yii\helpers\Url::toRoute(['/user/update','id'=>$data->id]));
                },
            ],
            [
                'attribute'=>'username',
                'format'=>'raw',
                'value'=>function($data){
                    return Html::a($data->username,\yii\helpers\Url::toRoute(['/user/update','id'=>$data->id]));
                },
            ],
            'email:email',
            [
                'attribute'=>'status',
                'format'=>'raw',
                'value'=>function($data){
                    return $data->getStatusLabel();
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
            ],
        ],
    ]); ?>

    </div>