frontend/controllers/PersonalController.php
<?php
namespace frontend\controllers;

use common\models\City;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;

use common\models\User;
use common\models\UserProfile;
use frontend\models\UserForm;

use vova07\fileapi\actions\UploadAction as FileAPIUpload;

/**
 * Class PersonalController
 * @package frontend\controllers
 */
class PersonalController extends Controller
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }



    public function actionIndex()
    {
        return $this->render('index');

    }
}

frontend/views/widgets/LoginWidget/login.php
<?php
use \yii\helpers\Html;
?>

<div class="profile-widget">
	<div class="top">
		<?= Html::a(Yii::$app->user->identity->username, '/personal/index', ['class' => 'user-name']); ?>
		<?= Html::a('Выход', '/logout', ['class' => 'btn-logout']); ?>
	</div>

	<!--div class="bottom">
		<big>23 500 руб.</big> + 450 баллов
	</div-->
</div>

frontend/views/widgets/LoginWidget/nologin.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="login-widget">
	<div class="buttons block">
		<?= Html::a('<i class="icon lock"></i>Вход', '#form-modal-signin', ['class'=>'btn-signin btn btn-primary left']); ?>
		<?= Html::a('Регистрация', '#form-modal-signup', ['class'=>'btn-signup right']); ?>
	</div>

</div>